<a href="https://colab.research.google.com/github/muratatk/-_CO2-_-_csv01/blob/main/%E3%82%A2%E3%83%9F%E3%83%B3_CO2%E5%9B%9E%E5%8F%8E_CSV_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install nlplot 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 967.9/967.9 KB 19.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 61.5 MB/s eta 0:00:00


In [ ]:
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#　csvは標準ライブラリとしてあるので、インストールする必要はない
#　CSVファイルの読み込み書き込み
# https://note.nkmk.me/python-csv-reader-writer/


In [ ]:
import pandas as pd
import matplotlib as plt
import os


In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
os.chdir('/content/drive/MyDrive/Python_Content/')

In [ ]:
!ls

2023-03-08_uni-gram.html  アミン_CO2回収_課題_日本語.csv
mecab-ipadic-neologd	  アミン_CO2回収_課題_日本語.txt
newplot.png


In [ ]:
pd.set_option('display.max_columns', 900) #DF定義：900行にしておく

In [ ]:
pd.set_option('display.max_colwidth',10000)

In [ ]:
!pip install janome

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 42.0 MB/s eta 0:00:00


In [ ]:
#　やっぱり、csvはインストールの必要なないが、importの必要はある
#　csvファイルの読み書き
#　https://www.tech-teacher.jp/blog/python-csv/

In [ ]:
import csv

In [ ]:
csvfile = open('/content/drive/MyDrive/Python_Content/アミン_CO2回収_課題_日本語.csv')

In [ ]:
for row in csv.reader(csvfile):
  print(row) 

['\ufeffid', 'text']
['1', '高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する']
['2', 'ＣＯ↓２吸収液を再生するための熱エネルギーと、回収したＣＯ↓２を圧縮する動力とを供給するとともに、高い熱効率を有するＣＯ↓２の回収方法及びそのシステムを提供する']
['3', '大規模二酸化炭素発生源から排出される二酸化炭素を、コンパクトな設備で効率的かつ安価に分離回収する技術を提供する']
['4', '中空糸状多孔膜を用いるガス分離方法及びその装置において、選択性、安定性及びガス分離速度の点ですぐれるとともに、従来の膜分離法と吸収法では達成し得なかったガス分離の大幅な所要エネルギー低減を図る']
['5', '酸性ガス除去装置１００は、希薄溶剤１２２および準希薄溶剤１３２を独立的に生成する２つの再生器１２０、１３０に濃厚溶剤１０６を供給する吸収器１１０を備え、準希薄溶剤１３２は、再生器の一方１３０において、他方の再生器１２０から誘導された熱１４０および／または蒸気２７６を使用して生成される']
['6', '窒素酸化物及び二酸化炭素を含有するガス中から二酸化窒素を効率良く除去することができ、かつ脱炭酸吸収液への窒素酸化物の蓄積を抑制することができる二酸化窒素と二酸化炭素の除去方法及びその装置を提供する']
['7', '煙道ガスから二酸化炭素を除去及び捕捉する方法であって：（ａ）溶媒抽出ゾーン（１）において煙道ガスを溶媒に接触させることにより煙道ガスから二酸化炭素を抽出して二酸化炭素の奪われた煙道ガスを得るステップ；（ｂ）二酸化炭素含有溶媒を溶媒再生温度に加熱しその温度で維持することにより溶媒再生ゾーン（２）内で溶媒を再生して再生溶媒と二酸化炭素流を得るステップ；及び（ｃ）ステップ（ｂ）で得られた二酸化炭素流を水溶液中に分散した２価アルカリ土類金属ケイ酸塩粒子と接触させることにより、鉱物炭酸塩化ゾーン（３）内で二酸化炭素流とケイ酸塩を反応させるステップを含む方法']
['8', 'エネルギー効率を一層向上させたＣＯ↓2回収装置及び方法を提供する']
['9', '煙道ガス、天然ガス、水素ガス、合成ガスから、およびその他のプロセスから、ならびに廃ガス流からＣＯ↓2を除去するために用

In [ ]:
# csvファイルをpandasで読み込む
#　https://blog.codecamp.jp/python-csv

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Python_Content/アミン_CO2回収_課題_日本語.csv')
print(df)

      id  \
0      1   
1      2   
2      3   
3      4   
4      5   
..   ...   
308  309   
309  310   
310  311   
311  312   
312  313   

                                                                                                                                                                                                                                                                                                                                                                                                        text  
0                                                                                                                                                                                                                                                                                                                                                     高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する  
1                                                        

In [ ]:
df

id  \
0      1   
1      2   
2      3   
3      4   
4      5   
..   ...   
308  309   
309  310   
310  311   
311  312   
312  313   

                                                                                                                                                                                                                                                                                                                                                                                                        text  
0                                                                                                                                                                                                                                                                                                                                                     高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する  
1                                                                                                                                                                                                                                                                                                                           ＣＯ↓２吸収液を再生するための熱エネルギーと、回収したＣＯ↓２を圧縮する動力とを供給するとともに、高い熱効率を有するＣＯ↓２の回収方法及びそのシステムを提供する  
2                                                                                                                                                                                                                                                                                                                                                    大規模二酸化炭素発生源から排出される二酸化炭素を、コンパクトな設備で効率的かつ安価に分離回収する技術を提供する  
3                                                                                                                                                                                                                                                                                                           中空糸状多孔膜を用いるガス分離方法及びその装置において、選択性、安定性及びガス分離速度の点ですぐれるとともに、従来の膜分離法と吸収法では達成し得なかったガス分離の大幅な所要エネルギー低減を図る  
4                                                                                                                                                                                                                                                             酸性ガス除去装置１００は、希薄溶剤１２２および準希薄溶剤１３２を独立的に生成する２つの再生器１２０、１３０に濃厚溶剤１０６を供給する吸収器１１０を備え、準希薄溶剤１３２は、再生器の一方１３０において、他方の再生器１２０から誘導された熱１４０および／または蒸気２７６を使用して生成される  
..                                                                                                                                                                                                                                                                                                                                                                                                       ...  
308  排ガスに含まれる炭酸ガスを吸収液に吸収させて炭酸ガス含有吸収液を生成する吸収塔と、吸収塔から供給された炭酸ガス含有吸収液を加熱し炭酸ガスを放出させて再生吸収液にする再生塔と、再生塔から供給された再生吸収液を加熱用水蒸気で加熱して再生塔に戻すリボイラーと、前記再生吸収液と前記炭酸ガス含有吸収液との間で熱交換する熱交換器と、熱交換器から送出された再生吸収液を予冷する再生吸収液冷却器と、駆動用水蒸気によって再生器が加熱され、熱交換器で昇温された炭酸ガス含有吸収液が供給され吸収器の伝熱管および凝縮器の伝熱管を介して再生塔に送出し、熱交換器および再生吸収液冷却器で降温された再生吸収液が供給され蒸発器の伝熱管を介して吸収塔に吸収液として環流させる吸収式ヒートポンプと、再生塔から炭酸ガスとともに供給された水蒸気を凝縮させて炭酸ガスを分離する炭酸ガス分離器と、を備える炭酸ガス回収システム  
309                             排ガスに含まれる炭酸ガスを吸収液に吸収させて二酸化炭素含有吸収液を生成する吸収塔と、吸収塔から供給された二酸化炭素含有吸収液を水蒸気で加熱し吸収した炭酸ガスの一部を放出させ二酸化炭素含有吸収液を二酸化炭素中間濃度吸収液にする高圧再生塔と、高圧再生塔から供給された二酸化炭素中間濃度吸収液を加熱し二酸化炭素中間濃度吸収液に残存する二酸化炭素の残部を放出させ二酸化炭素中間濃度吸収液を再生吸収液にする低圧再生塔と、低圧再生塔から供給された再生吸収液と吸収塔から供給された二酸化炭素含有吸収液との間で熱交換する第１熱交換器と、高圧再生塔から流出し低圧再生塔に流入する二酸化炭素中間濃度吸収液と第１熱交換器から流出し高圧再生塔に流入する二酸化炭素含有吸収液との間で熱交換させる第２熱交換器とを備える二重効用化学吸収式炭酸ガス回収システム  
310                                                                           二酸化炭素を含有する被分離ガス（例えば燃焼排ガス）から二酸化炭素を分離する分離装置（６０）を備える二酸化炭素回収装置（１Ａ）において、被分離ガスが供給される上流側から順に、分離装置（６０）と、分離装置（６０）において分離された二酸化炭素を昇華（固化）させる二酸化炭素昇華器（５Ａ，５Ｂ）と、が直列に接続されていること、二酸化炭素昇華器（５Ａ，５Ｂ）には、冷熱を有する流体を冷媒とする冷

In [ ]:
!pip install janome

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from janome.tokenizer import Tokenizer

In [ ]:
t = Tokenizer(wakati=True)

In [ ]:
# dfデータフレーム操作　https://rinsaka.com/python/hyaku/02-janome.html

In [ ]:
df[df.index == 0]

id                                                    text
0   1  高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する

In [ ]:
df[df.index == 1]

id  \
1   2   

                                                                               text  
1  ＣＯ↓２吸収液を再生するための熱エネルギーと、回収したＣＯ↓２を圧縮する動力とを供給するとともに、高い熱効率を有するＣＯ↓２の回収方法及びそのシステムを提供する

In [ ]:
df[df.index == 1][['id','text']]

id  \
1   2   

                                                                               text  
1  ＣＯ↓２吸収液を再生するための熱エネルギーと、回収したＣＯ↓２を圧縮する動力とを供給するとともに、高い熱効率を有するＣＯ↓２の回収方法及びそのシステムを提供する

In [ ]:
df[df.index == 2][['id','text']]

id                                                     text
2   3  大規模二酸化炭素発生源から排出される二酸化炭素を、コンパクトな設備で効率的かつ安価に分離回収する技術を提供する

In [ ]:
text = df.loc[:, ['id','text']].values

In [ ]:
text

array([[1, '高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する'],
       [2,
        'ＣＯ↓２吸収液を再生するための熱エネルギーと、回収したＣＯ↓２を圧縮する動力とを供給するとともに、高い熱効率を有するＣＯ↓２の回収方法及びそのシステムを提供する'],
       [3, '大規模二酸化炭素発生源から排出される二酸化炭素を、コンパクトな設備で効率的かつ安価に分離回収する技術を提供する'],
       [4,
        '中空糸状多孔膜を用いるガス分離方法及びその装置において、選択性、安定性及びガス分離速度の点ですぐれるとともに、従来の膜分離法と吸収法では達成し得なかったガス分離の大幅な所要エネルギー低減を図る'],
       [5,
        '酸性ガス除去装置１００は、希薄溶剤１２２および準希薄溶剤１３２を独立的に生成する２つの再生器１２０、１３０に濃厚溶剤１０６を供給する吸収器１１０を備え、準希薄溶剤１３２は、再生器の一方１３０において、他方の再生器１２０から誘導された熱１４０および／または蒸気２７６を使用して生成される'],
       [6,
        '窒素酸化物及び二酸化炭素を含有するガス中から二酸化窒素を効率良く除去することができ、かつ脱炭酸吸収液への窒素酸化物の蓄積を抑制することができる二酸化窒素と二酸化炭素の除去方法及びその装置を提供する'],
       [7,
        '煙道ガスから二酸化炭素を除去及び捕捉する方法であって：（ａ）溶媒抽出ゾーン（１）において煙道ガスを溶媒に接触させることにより煙道ガスから二酸化炭素を抽出して二酸化炭素の奪われた煙道ガスを得るステップ；（ｂ）二酸化炭素含有溶媒を溶媒再生温度に加熱しその温度で維持することにより溶媒再生ゾーン（２）内で溶媒を再生して再生溶媒と二酸化炭素流を得るステップ；及び（ｃ）ステップ（ｂ）で得られた二酸化炭素流を水溶液中に分散した２価アルカリ土類金属ケイ酸塩粒子と接触させることにより、鉱物炭酸塩化ゾーン（３）内で二酸化炭素流とケイ酸塩を反応させるステップを含む方法'],
       [8, 'エネルギー効率を一層向上させたＣＯ↓2回収装置及び方法を提供する'],

In [ ]:
def my_Janome(text):
    t = Tokenizer()
    results = t.tokenize(text)
    for token in results:
        print(token)

In [ ]:
text[0][1]

'高効率運転を図りつつ、炭酸ガス（例えば、二酸化炭素）を効率良く除去することができるガスタービン装置を提供する'

In [ ]:
my_Janome(text[0][1])

高	接頭詞,名詞接続,*,*,*,*,高,コウ,コー
効率	名詞,一般,*,*,*,*,効率,コウリツ,コーリツ
運転	名詞,サ変接続,*,*,*,*,運転,ウンテン,ウンテン
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
図り	動詞,自立,*,*,五段・ラ行,連用形,図る,ハカリ,ハカリ
つつ	助詞,接続助詞,*,*,*,*,つつ,ツツ,ツツ
、	記号,読点,*,*,*,*,、,、,、
炭酸	名詞,一般,*,*,*,*,炭酸,タンサン,タンサン
ガス	名詞,一般,*,*,*,*,ガス,ガス,ガス
（	記号,括弧開,*,*,*,*,（,（,（
例えば	接続詞,*,*,*,*,*,例えば,タトエバ,タトエバ
、	記号,読点,*,*,*,*,、,、,、
二酸化炭素	名詞,一般,*,*,*,*,二酸化炭素,ニサンカタンソ,ニサンカタンソ
）	記号,括弧閉,*,*,*,*,）,）,）
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
効率	名詞,一般,*,*,*,*,効率,コウリツ,コーリツ
良く	形容詞,自立,*,*,形容詞・アウオ段,連用テ接続,良い,ヨク,ヨク
除去	名詞,サ変接続,*,*,*,*,除去,ジョキョ,ジョキョ
する	動詞,自立,*,*,サ変・スル,基本形,する,スル,スル
こと	名詞,非自立,一般,*,*,*,こと,コト,コト
が	助詞,格助詞,一般,*,*,*,が,ガ,ガ
できる	動詞,自立,*,*,一段,基本形,できる,デキル,デキル
ガス	名詞,一般,*,*,*,*,ガス,ガス,ガス
タービン	名詞,一般,*,*,*,*,タービン,タービン,タービン
装置	名詞,サ変接続,*,*,*,*,装置,ソウチ,ソーチ
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
提供	名詞,サ変接続,*,*,*,*,提供,テイキョウ,テイキョー
する	動詞,自立,*,*,サ変・スル,基本形,する,スル,スル


In [ ]:
def wakati(text):
    t = Tokenizer()
    results = t.tokenize(text)
    words = []
    for token in results:
        words.append(token.surface) # 表層形
    return words

In [ ]:
words_0 = wakati(text[0][1])

In [ ]:
print(words_0)

['高', '効率', '運転', 'を', '図り', 'つつ', '、', '炭酸', 'ガス', '（', '例えば', '、', '二酸化炭素', '）', 'を', '効率', '良く', '除去', 'する', 'こと', 'が', 'できる', 'ガス', 'タービン', '装置', 'を', '提供', 'する']


In [ ]:
%%time
text_wakati = []
for i in range(text.shape[0]):
    w = wakati(text[i][1])
    text_wakati.append(w)
print(text_wakati)

[['高', '効率', '運転', 'を', '図り', 'つつ', '、', '炭酸', 'ガス', '（', '例えば', '、', '二酸化炭素', '）', 'を', '効率', '良く', '除去', 'する', 'こと', 'が', 'できる', 'ガス', 'タービン', '装置', 'を', '提供', 'する'], ['ＣＯ', '↓', '２', '吸収', '液', 'を', '再生', 'する', 'ため', 'の', '熱', 'エネルギー', 'と', '、', '回収', 'し', 'た', 'ＣＯ', '↓', '２', 'を', '圧縮', 'する', '動力', 'と', 'を', '供給', 'する', 'とともに', '、', '高い', '熱', '効率', 'を', '有する', 'ＣＯ', '↓', '２', 'の', '回収', '方法', '及び', 'その', 'システム', 'を', '提供', 'する'], ['大', '規模', '二酸化炭素', '発生', '源', 'から', '排出', 'さ', 'れる', '二酸化炭素', 'を', '、', 'コンパクト', 'な', '設備', 'で', '効率', '的', 'かつ', '安価', 'に', '分離', '回収', 'する', '技術', 'を', '提供', 'する'], ['中空', '糸状', '多孔', '膜', 'を', '用いる', 'ガス', '分離', '方法', '及び', 'その', '装置', 'において', '、', '選択', '性', '、', '安定', '性', '及び', 'ガス', '分離', '速度', 'の', '点', 'で', 'すぐれる', 'とともに', '、', '従来', 'の', '膜', '分離', '法', 'と', '吸収', '法', 'で', 'は', '達成', 'し', '得', 'なかっ', 'た', 'ガス', '分離', 'の', '大幅', 'な', '所要', 'エネルギー', '低減', 'を', '図る'], ['酸性', 'ガス', '除去', '装置', '１', '０', '０', 'は', '、', '希薄', '溶剤', '１', '２', '２', '

In [ ]:
import itertools # 2次元リストを1次元化

In [ ]:
# 索引語の集合を作りたいので，その前に上の2次元リストを1次元化します．なお，途中（100個目）まで表示したあと，全体の個数を表示すると16394 個であることがわかります．

In [ ]:
words = list(itertools.chain.from_iterable(text_wakati))
print(words[0:100])
print(len(words))

['高', '効率', '運転', 'を', '図り', 'つつ', '、', '炭酸', 'ガス', '（', '例えば', '、', '二酸化炭素', '）', 'を', '効率', '良く', '除去', 'する', 'こと', 'が', 'できる', 'ガス', 'タービン', '装置', 'を', '提供', 'する', 'ＣＯ', '↓', '２', '吸収', '液', 'を', '再生', 'する', 'ため', 'の', '熱', 'エネルギー', 'と', '、', '回収', 'し', 'た', 'ＣＯ', '↓', '２', 'を', '圧縮', 'する', '動力', 'と', 'を', '供給', 'する', 'とともに', '、', '高い', '熱', '効率', 'を', '有する', 'ＣＯ', '↓', '２', 'の', '回収', '方法', '及び', 'その', 'システム', 'を', '提供', 'する', '大', '規模', '二酸化炭素', '発生', '源', 'から', '排出', 'さ', 'れる', '二酸化炭素', 'を', '、', 'コンパクト', 'な', '設備', 'で', '効率', '的', 'かつ', '安価', 'に', '分離', '回収', 'する', '技術']
16394


In [ ]:
# 次のコードを実行することで単語（索引語）の集合を作ることができます．この結果，1162の索引語が使われていることがわかりました．

In [ ]:
vocab = sorted(set(words))
print(vocab)
print(len(vocab))

['(', ')', ')↓', ',', '-', '-(', '0', '1', '10', '100', '12', '14', '2', '22', '26', '28', '3', '34', '4', '60', '90', '?', 'CH', 'CO', 'N', 'NH', 'NR', 'OH', 'R', 'X', 'bar', 'm', 'n', '×', 'μ', '℃', '↑', '↓', '↓-↓', '↓～↓', '、', '【', '】', '〔', '〕', 'あたり', 'あっ', 'あり', 'ある', 'い', 'いる', 'うる', 'および', 'おり', 'か', 'かかる', 'かける', 'かつ', 'から', 'が', 'ここ', 'こと', 'この', 'これ', 'これら', 'さ', 'させ', 'さらに', 'し', 'しかも', 'じん', 'すぐれる', 'すなわち', 'する', 'ず', 'せ', 'せる', 'そして', 'その', 'その他', 'その後', 'それ', 'それぞれ', 'それら', 'た', 'ただし', 'ため', 'だ', 'だけ', 'つ', 'つつ', 'て', 'で', 'でき', 'できる', 'でも', 'と', 'という', 'とき', 'として', 'とともに', 'と共に', 'な', 'ない', 'ないし', 'なかっ', 'ながら', 'なく', 'など', 'なら', 'ならびに', 'なり', 'なる', 'に', 'において', 'における', 'について', 'にて', 'によって', 'により', 'による', 'に対し', 'に対して', 'に対する', 'に関し', 'に関する', 'に際し', 'の', 'のみ', 'は', 'ばい', 'びこのような', 'へ', 'ほとんど', 'ほぼ', 'また', 'または', 'まで', 'も', 'もたらす', 'もの', 'や', 'よう', 'よく', 'より', 'られ', 'られる', 'れ', 'れる', 'ろ過', 'を', 'アノード', 'アミ', 'アミン', 'アミンガス', 'アミンスクラビング', 'アルカノールアミン', 'アルカリ', 'アルキリデンアミノグアニジ

In [ ]:
import numpy as np

In [ ]:
# 索引後の頻度 TF (Term Frequency) を求める関数を定義します．

In [ ]:
def get_TF(text_wakati, vocab):
    """
    TFは索引語の出現頻度のこと．
    """
    n_docs = len(text_wakati)
    n_vocab = len(vocab)
 
    # 行数 = 文書数， 列数 = 登録集合数 で tf を初期化する
    tf = np.zeros((n_docs, n_vocab))
 
    for i in range(n_docs):
        for w in text_wakati[i]:
            tf[i, vocab.index(w)] += 1
    return tf

In [ ]:
# 上で定義した関数 get_TF に分かち書きした結果と索引語一覧を与えて，索引語頻度を求めます

In [ ]:
tf = get_TF(text_wakati, vocab)
print(tf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# 行列 tf のサイズを確認すると，313行 x 1162列であることがわかります．

In [ ]:
tf.shape

(313, 1162)

In [ ]:
# わからん

In [ ]:
print(tf[10])

[0. 0. 0. ... 0. 0. 0.]


In [ ]:
print(vocab[0], tf[0][0])
print(vocab[10], tf[0][10])
print(vocab[212], tf[0][212])

( 0.0
12 0.0
ノズル 0.0


In [ ]:
#　これで分析に必要な索引語頻度の2次元配列 tf を生成できました．

In [ ]:
tf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#　索引後の集合
'''
', '洗浄液', '活性', '活性炭', '活用', '流', '流さ', '流す', '流れ', '流れる', '流体', '流入', '流出', '流動的', '流通', '流量', '浄化', '海水', '消費', '液', '液体', '液状', '混合', '添加', '清掃', '済', '済み', '減らす', '減圧', '減少', '渣', '温', '温室', '温度', '測定', '湾曲', '湿式', '湿潤', '満足', '源', '準', '溶剤', '溶媒', '溶存', '溶液', '溶解', '濃厚', '濃度', '濃縮', '濡れ', '火力', '炉', '炭化', '炭素', '炭酸', '点', '点在', '焚き', '無く', '無機', '無駄', '焼却', '煙', '煙突', '煤', '熱', '熱源', '熱量', '熱風', '燃料', '燃焼', '物', '物品', '物理', '物質', '特に', '特定', '特徴', '特殊', '特許', '状', '状態', '独立', '率', '環', '環境', '生', '生さ', '生し', '生じ', '生成', '生物', '生産', '生育', '用', '用い', '用いる', '由来', '画', '異なる', '発揮', '発明', '発泡', '発熱', '発生', '発酵', '発電', '的', '目的', '直列', '直径', '直線', '相', '相互', '省エネルギー', '真空', '着', '着用', '着色', '短時間', '石炭', '硫黄', '確保', '確実', '示す', '移動', '移送', '種', '稼働', '空き', '空間', '空隙', '窒素', '立', '立体', '第', '等', '管', '管理', '範囲', '簡便', '簡単', '簡易', '粒', '粒子', '粗', '粘', '精度', '精製', '糸状', '系', '約', '純度', '純粋', '級', '細', '組み合わせ', '組成', '経時', '経済', '経路', '経過', '結合', '結果', '給', '給油', '統合', '継続', '続く', '維持', '総合', '緩和', '縮小', '置換', '群', '考慮', '者', '耐え', '耐久', '耐摩耗', '耐熱', '肥大', '能', '能力', '脂肪', '脱', '脱去', '脱着', '脱硫', '腐食', '膜', '膨大', '自動的', '臭', '良い', '良く', '良好', '芳香', '蒸散', '蒸気', '蒸発', '蓄積', '薄', '行う', '行える', '行っ', '行ない', '行わ', '表さ', '表示', '表面', '被', '装置', '補助', '補給', '製品', '製造', '製鉄', '複合', '複数', '要する', '要求', '要素', '規定', '規模', '親水', '解決', '解消', '触媒', '記載', '設', '設け', '設備', '設定', '設置', '該', '該分解', '該含水', '該吸収', '該吸着', '該排', '該方法', '該煙道', '詳しく', '誘導', '課題', '調整', '調節', '調製', '負', '負荷', '貯留', '貯蔵', '費', '費用', '質', '質量', '走行', '起因', '距離', '路', '路上', '車両', '軽減', '輸送', '農産物', '迅速', '近傍', '追加', '追従', '送', '送ら', '送出', '通', '通し', '通っ', '通気', '通路', '通過', '速やか', '速度', '連', '連結', '連続', '遊離', '運び', '運び出さ', '運用', '運転', '過程', '道', '達成', '遠心', '適し', '適切', '適正', '適用', '選ば', '選択', '避ける', '還元', '還流', '部', '部位', '部内', '部分', '部屋', '部材', '配管', '配置', '酸', '酸化', '酸性', '酸素', '重', '重量', '量', '金属', '鉄', '鉱物', '長時間', '長期', '長期間', '閉塞', '開放', '開示', '間', '防ぎ', '防ぐ', '防止', '降', '限り', '限界', '除', '除去', '隔離', '際', '障害', '集', '集計', '離', '離し', '離れ', '離脱', '電', '電力', '電極', '電池', '電源', '電解', '露点', '非', '面', '頂', '順に', '領域', '頻度', '顕', '類', '飛散', '飛沫', '飛躍', '飽和', '駆動', '高', '高い', '高く', '高める', '高分子', '高圧', '高温', '高炉', '％', '（', '）', '，', '－', '．', '／', '０', '１', '１つ', '２', '２つ', '３', '４', '５', '６', '７', '８', '９', '：', '；', '＜', 'Ａ', 'Ｂ', 'ＢＩＣＩＮＥ', 'Ｃ', 'ＣＯ', 'ＣＯ２', 'ＣＲ', 'Ｄ', 'Ｈ', 'Ｋ', 'Ｌ', 'Ｍ', 'Ｎ', 'ＮＯ', 'ＮＯｘ', 'Ｏ', 'Ｐ', 'Ｐａ', 'Ｒ', 'Ｓ', 'ＳＯ', 'ＳＯｘ', 'ＶＯＣ', 'Ｖｄ', 'ＷＯ', 'Ｘ', '［', '］', 'ａ', 'ｂ', 'ｃ', 'ｃｍ', 'ｇ', 'ｉ', 'ｍ', 'ｎ', 'ｎｍ', 'ｏ', 'ｐＫａ', 'ｐｐｍ', 'ｗ', 'ｘ', '～', '～↓']
1162
'''